apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-db-deployment
  labels:
    app: basic-db
spec:
  replicas: 10
  selector:
    matchLabels:
      app: basic-db-pod
  template:
    metadata:
      labels:
        app: basic-db-pod
    spec:
      containers:
      - name: basic-db
        image: 192.168.0.16:5000/basic_db:0.0.1
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: codeverse-secret
